### ISSUE TITLE
Hive Tracking Navigation

### ISSUE THREAD

**Issue by anthonyfabius** [evearwen/BeeKeepr#7]
The Hive tracking feature allows a user to keep track of information pertaining to their beehives. Since there is no backend at the current moment most of this will be eye candy that is deleted the moment you exit a page. Below are the specifications for navigation of the feature.

### Data Tab
When a user initially clicks on the data tracking tab from the home page this is what they will see. A list of hives they are currently tracking along with a button to add new hives. A user can then select a hive or the button to create a new one.

For this tab to be finished all of the following must be ticked
- [x] A bunch of fake hives
  - [x] Clicking on one of these will enter the Hive Tab
- [x] New Hive button
  - [x] Navigate to New Hive Tab
  - [x] Stick to bottom of page
- [x] UI/UX mostly adheres to current design

### Hive Tab
When a user is viewing information about a hive this tab is what they are looking at. A user can select a specific entry to enter/edit

For this tab to be finished all of the following must be ticked
- [x] Fake entries
  - [ ] Brief summary of entries
    - [ ] Maybe icons if something appears. Like a crown if the queen was seen or a skull if there was a disease
- [x] New Entry Button
  - [x] Navigate to Hive Data Entry Tab
  - [x] Stick to bottom of page
- [ ] Tags (pain)
- [x] UI/UX mostly adheres to current design

### Hive Data Entry Tab
This page is where a user inputs information for a hive entry. They list if they have seen the queen, brood, honey/pollen, etc. As well as a section for notes and pictures for additional tracking.

For this tab to be finished all of the following must be ticked
- [x] Data Tracking
  - [x] Queen Status
  - [ ] Brood
  - [x] Honey & Pollen
  - [ ] Varroa mite level?
  - [ ] Various diseases
- [x] A way to input pictures - they won't be saved
- [x] Save changes button - no functionality
- [x] UI/UX mostly adheres to current design

### Hive New/Edit Tab
This page is where a user can create and edit a new hive. They can input information like the hive name, location, type, # of deeps, supers, and frames, etc.

For this tab to be finished all of the following must be ticked
- [x] Information Fields
  - [x] Hive Name, Type, Location, Color
  - [x] # of Deeps, Supers, & Frames
  - [x] Queen breed & color
  - [x] Notes
- [x] Save changes button - no functionality
- [x] UI/UX mostly adheres to current design

Current Designs:
<p>
  <img src="https://github.com/user-attachments/assets/b18aa359-400c-4381-8da8-5283afe612db" height=300 title="Data Tab">
  <img src="https://github.com/user-attachments/assets/87e79e4e-4976-479d-8ccc-c660d41257e4" height=300 title="Hive Tab">
  <img src="https://github.com/user-attachments/assets/7e080923-d966-41cf-bce7-a6bf7996e81d" height=300 title="Hive Data Entry Tab">
  <img src="https://github.com/user-attachments/assets/764e8668-f6e9-40fd-b019-27101674c858" height=300 title="Hive New/Edit Tab">
</p>
